[package]
name = "spades"
version = "0.1.0"
authors = ["Tom Colen <tcolen@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
playing-cards = { path = "../playing-cards" }
